data = [
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "AAPL", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "AAPL",
        },
        "Quick": {
            "change": 0.672,
            "changePct": 0.3757,
            "lastTrade": 179.522,
            "lastTradeTime": 1691521659,
            "quoteStatus": "DELAYED",
            "volume": 50317947,
        },
        "adjPrevClose": 178.85,
        "commissions": 0,
        "costPerShare": 126.875,
        "dateAcquired": 1615525200000,
        "daysGain": 1.344,
        "daysGainPct": 0.3757,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155837183900.json",
        "marketValue": 359.0439,
        "otherFees": 0,
        "pctOfPortfolio": 2.3942,
        "positionId": 155837183900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 126.875,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/AAPL.json",
        "symbolDescription": "AAPL",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 253.75,
        "totalGain": 105.2939,
        "totalGainPct": 41.4951,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "MBSC", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "MBSC",
        },
        "Quick": {
            "change": -0.01,
            "changePct": -0.0953,
            "lastTrade": 10.48,
            "lastTradeTime": 1691520619,
            "quoteStatus": "DELAYED",
            "volume": 1356608,
        },
        "adjPrevClose": 10.49,
        "commissions": 0,
        "costPerShare": 10.39,
        "dateAcquired": 1683777600000,
        "daysGain": -0.05,
        "daysGainPct": -0.0953,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/316596452900.json",
        "marketValue": 52.3999,
        "otherFees": 0,
        "pctOfPortfolio": 0.3494,
        "positionId": 316596452900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 10.39,
        "quantity": 5,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/MBSC.json",
        "symbolDescription": "MBSC",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 51.95,
        "totalGain": 0.45,
        "totalGainPct": 0.8662,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "MMM", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "MMM",
        },
        "Quick": {
            "change": -1.37,
            "changePct": -1.3019,
            "lastTrade": 103.86,
            "lastTradeTime": 1691521657,
            "quoteStatus": "DELAYED",
            "volume": 2086441,
        },
        "adjPrevClose": 105.23,
        "commissions": 0,
        "costPerShare": 196.63,
        "dateAcquired": 1624334400000,
        "daysGain": -2.74,
        "daysGainPct": -1.3019,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181284159900.json",
        "marketValue": 207.7199,
        "otherFees": 0,
        "pctOfPortfolio": 1.3851,
        "positionId": 181284159900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 196.6299,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/MMM.json",
        "symbolDescription": "MMM",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 393.2599,
        "totalGain": -185.5399,
        "totalGainPct": -47.1799,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "MRK", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "MRK",
        },
        "Quick": {
            "change": 0.355,
            "changePct": 0.3346,
            "lastTrade": 106.445,
            "lastTradeTime": 1691521656,
            "quoteStatus": "DELAYED",
            "volume": 6820564,
        },
        "adjPrevClose": 106.09,
        "commissions": 0,
        "costPerShare": 73.305,
        "dateAcquired": 1615525200000,
        "daysGain": 0.7099,
        "daysGainPct": 0.3346,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155842604900.json",
        "marketValue": 212.8899,
        "otherFees": 0,
        "pctOfPortfolio": 1.4196,
        "positionId": 155842604900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 73.305,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/MRK.json",
        "symbolDescription": "MRK",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 146.61,
        "totalGain": 66.28,
        "totalGainPct": 45.2083,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "MSFT", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "MSFT",
        },
        "Quick": {
            "change": -5.1,
            "changePct": -1.5449,
            "lastTrade": 325.01,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 14906449,
        },
        "adjPrevClose": 330.11,
        "commissions": 0,
        "costPerShare": 270.5,
        "dateAcquired": 1625025600000,
        "daysGain": -5.0999,
        "daysGainPct": -1.5449,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/183181815900.json",
        "marketValue": 325.0099,
        "otherFees": 0,
        "pctOfPortfolio": 2.1672,
        "positionId": 183181815900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 270.5,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/MSFT.json",
        "symbolDescription": "MSFT",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 270.5,
        "totalGain": 54.5099,
        "totalGainPct": 20.1515,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "NKE", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "NKE",
        },
        "Quick": {
            "change": -1.12,
            "changePct": -1.0137,
            "lastTrade": 109.36,
            "lastTradeTime": 1691521653,
            "quoteStatus": "DELAYED",
            "volume": 3766713,
        },
        "adjPrevClose": 110.48,
        "commissions": 0,
        "costPerShare": 153.94,
        "dateAcquired": 1625112000000,
        "daysGain": -1.12,
        "daysGainPct": -1.0137,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/183480075900.json",
        "marketValue": 109.3599,
        "otherFees": 0,
        "pctOfPortfolio": 0.7292,
        "positionId": 183480075900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 153.9399,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/NKE.json",
        "symbolDescription": "NKE",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 153.9399,
        "totalGain": -44.5799,
        "totalGainPct": -28.9593,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "PG", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "PG",
        },
        "Quick": {
            "change": 0.38,
            "changePct": 0.2421,
            "lastTrade": 157.3,
            "lastTradeTime": 1691521656,
            "quoteStatus": "DELAYED",
            "volume": 2850743,
        },
        "adjPrevClose": 156.92,
        "commissions": 0,
        "costPerShare": 132.35,
        "dateAcquired": 1615525200000,
        "daysGain": 0.76,
        "daysGainPct": 0.2421,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155854197900.json",
        "marketValue": 314.6,
        "otherFees": 0,
        "pctOfPortfolio": 2.0978,
        "positionId": 155854197900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 132.3499,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/PG.json",
        "symbolDescription": "PG",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 264.6999,
        "totalGain": 49.8999,
        "totalGainPct": 18.8515,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "QQQM", "typeCode": "EQUITY"},
            "securitySubType": "ETF",
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "QQQM",
        },
        "Quick": {
            "change": -1.47,
            "changePct": -0.9525,
            "lastTrade": 152.85,
            "lastTradeTime": 1691521650,
            "quoteStatus": "DELAYED",
            "volume": 773315,
        },
        "adjPrevClose": 154.32,
        "commissions": 0,
        "costPerShare": 157.705,
        "dateAcquired": 1690776000000,
        "daysGain": -23.5199,
        "daysGainPct": -0.9525,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/330561839900.json",
        "marketValue": 2445.5999,
        "otherFees": 0,
        "pctOfPortfolio": 16.3079,
        "positionId": 330561839900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 157.705,
        "quantity": 16,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/QQQM.json",
        "symbolDescription": "QQQM",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 2523.28,
        "totalGain": -77.68,
        "totalGainPct": -3.0785,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "RBLX", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "RBLX",
        },
        "Quick": {
            "change": 0.335,
            "changePct": 0.8909,
            "lastTrade": 37.935,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 9137565,
        },
        "adjPrevClose": 37.6,
        "commissions": 0,
        "costPerShare": 78.435,
        "dateAcquired": 1627444800000,
        "daysGain": 0.67,
        "daysGainPct": 0.8909,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/189455662900.json",
        "marketValue": 75.87,
        "otherFees": 0,
        "pctOfPortfolio": 0.5059,
        "positionId": 189455662900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 78.435,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/RBLX.json",
        "symbolDescription": "RBLX",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 156.87,
        "totalGain": -81,
        "totalGainPct": -51.6351,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "T", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "T",
        },
        "Quick": {
            "change": 0.17,
            "changePct": 1.2134,
            "lastTrade": 14.18,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 26745286,
        },
        "adjPrevClose": 14.01,
        "commissions": 0,
        "costPerShare": 21.4933,
        "dateAcquired": 1624334400000,
        "daysGain": 1.02,
        "daysGainPct": 1.2134,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181295846900.json",
        "marketValue": 85.0799,
        "otherFees": 0,
        "pctOfPortfolio": 0.5673,
        "positionId": 181295846900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 21.4933,
        "quantity": 6,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/T.json",
        "symbolDescription": "T",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 128.9599,
        "totalGain": -43.8799,
        "totalGainPct": -34.026,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "LOW", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "LOW",
        },
        "Quick": {
            "change": -2.22,
            "changePct": -0.9941,
            "lastTrade": 221.08,
            "lastTradeTime": 1691521650,
            "quoteStatus": "DELAYED",
            "volume": 1348322,
        },
        "adjPrevClose": 223.3,
        "commissions": 0,
        "costPerShare": 192.555,
        "dateAcquired": 1624334400000,
        "daysGain": -4.44,
        "daysGainPct": -0.9941,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181286552900.json",
        "marketValue": 442.16,
        "otherFees": 0,
        "pctOfPortfolio": 2.9484,
        "positionId": 181286552900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 192.555,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/LOW.json",
        "symbolDescription": "LOW",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 385.11,
        "totalGain": 57.0499,
        "totalGainPct": 14.8139,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "KMX", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "KMX",
        },
        "Quick": {
            "change": 1.05,
            "changePct": 1.2389,
            "lastTrade": 85.8,
            "lastTradeTime": 1691521640,
            "quoteStatus": "DELAYED",
            "volume": 463495,
        },
        "adjPrevClose": 84.75,
        "commissions": 0,
        "costPerShare": 129.5,
        "dateAcquired": 1625112000000,
        "daysGain": 1.05,
        "daysGainPct": 1.2389,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/183475278900.json",
        "marketValue": 85.7999,
        "otherFees": 0,
        "pctOfPortfolio": 0.5721,
        "positionId": 183475278900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 129.5,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/KMX.json",
        "symbolDescription": "KMX",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 129.5,
        "totalGain": -43.7,
        "totalGainPct": -33.7451,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "ABBV", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "ABBV",
        },
        "Quick": {
            "change": -0.44,
            "changePct": -0.2926,
            "lastTrade": 149.89,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 2243273,
        },
        "adjPrevClose": 150.33,
        "commissions": 0,
        "costPerShare": 113.8133,
        "dateAcquired": 1615525200000,
        "daysGain": -1.32,
        "daysGainPct": -0.2926,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155793815900.json",
        "marketValue": 449.67,
        "otherFees": 0,
        "pctOfPortfolio": 2.9985,
        "positionId": 155793815900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 113.8133,
        "quantity": 3,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/ABBV.json",
        "symbolDescription": "ABBV",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 341.4399,
        "totalGain": 108.23,
        "totalGainPct": 31.6981,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "AXP", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "AXP",
        },
        "Quick": {
            "change": -1.5,
            "changePct": -0.8984,
            "lastTrade": 165.46,
            "lastTradeTime": 1691521652,
            "quoteStatus": "DELAYED",
            "volume": 1301905,
        },
        "adjPrevClose": 166.96,
        "commissions": 0,
        "costPerShare": 164.6766,
        "dateAcquired": 1615525200000,
        "daysGain": -4.5,
        "daysGainPct": -0.8984,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155846413900.json",
        "marketValue": 496.3799,
        "otherFees": 0,
        "pctOfPortfolio": 3.31,
        "positionId": 155846413900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 164.6766,
        "quantity": 3,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/AXP.json",
        "symbolDescription": "AXP",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 494.0299,
        "totalGain": 2.35,
        "totalGainPct": 0.4756,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "BRK.B", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "BRK.B",
        },
        "Quick": {
            "change": 1.24,
            "changePct": 0.3419,
            "lastTrade": 363.82,
            "lastTradeTime": 1691521655,
            "quoteStatus": "DELAYED",
            "volume": 2291741,
        },
        "adjPrevClose": 362.58,
        "commissions": 0,
        "costPerShare": 276.98,
        "dateAcquired": 1624334400000,
        "daysGain": 1.2399,
        "daysGainPct": 0.3419,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181291257900.json",
        "marketValue": 363.8199,
        "otherFees": 0,
        "pctOfPortfolio": 2.426,
        "positionId": 181291257900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 276.98,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/BRK.B.json",
        "symbolDescription": "BRK.B",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 276.98,
        "totalGain": 86.84,
        "totalGainPct": 31.3524,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "CSCO", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "CSCO",
        },
        "Quick": {
            "change": -0.015,
            "changePct": -0.0282,
            "lastTrade": 52.995,
            "lastTradeTime": 1691521657,
            "quoteStatus": "DELAYED",
            "volume": 6576213,
        },
        "adjPrevClose": 53.01,
        "commissions": 0,
        "costPerShare": 52.025,
        "dateAcquired": 1615525200000,
        "daysGain": -0.0599,
        "daysGainPct": -0.0282,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155835686900.json",
        "marketValue": 211.9799,
        "otherFees": 0,
        "pctOfPortfolio": 1.4135,
        "positionId": 155835686900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 52.0249,
        "quantity": 4,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/CSCO.json",
        "symbolDescription": "CSCO",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 208.0999,
        "totalGain": 3.8799,
        "totalGainPct": 1.8644,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "DIS", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "DIS",
        },
        "Quick": {
            "change": 0.8717,
            "changePct": 1.0039,
            "lastTrade": 87.7017,
            "lastTradeTime": 1691521659,
            "quoteStatus": "DELAYED",
            "volume": 10093758,
        },
        "adjPrevClose": 86.83,
        "commissions": 0,
        "costPerShare": 168.8166,
        "dateAcquired": 1624334400000,
        "daysGain": 2.615,
        "daysGainPct": 1.0039,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181299885900.json",
        "marketValue": 263.105,
        "otherFees": 0,
        "pctOfPortfolio": 1.7544,
        "positionId": 181299885900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 168.8166,
        "quantity": 3,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/DIS.json",
        "symbolDescription": "DIS",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 506.4499,
        "totalGain": -243.3448,
        "totalGainPct": -48.0491,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "FDX", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "FDX",
        },
        "Quick": {
            "change": 4.57,
            "changePct": 1.7287,
            "lastTrade": 268.93,
            "lastTradeTime": 1691521657,
            "quoteStatus": "DELAYED",
            "volume": 1482880,
        },
        "adjPrevClose": 264.36,
        "commissions": 0,
        "costPerShare": 296.06,
        "dateAcquired": 1625025600000,
        "daysGain": 4.57,
        "daysGainPct": 1.7287,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/183207479900.json",
        "marketValue": 268.93,
        "otherFees": 0,
        "pctOfPortfolio": 1.7933,
        "positionId": 183207479900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 296.06,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/FDX.json",
        "symbolDescription": "FDX",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 296.06,
        "totalGain": -27.1299,
        "totalGainPct": -9.1636,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "FXAIX", "typeCode": "MUTUAL_FUND"},
            "securityType": "MF",
            "strikePrice": 0,
            "symbol": "FXAIX",
        },
        "Quick": {
            "change": 1.41,
            "changePct": 0.9065,
            "lastTrade": 156.94,
            "lastTradeTime": 1691409900,
            "quoteStatus": "REALTIME",
            "volume": 0,
        },
        "adjPrevClose": 155.53,
        "commissions": 0,
        "costPerShare": 159.3574,
        "dateAcquired": 1690776000000,
        "daysGain": 22.12,
        "daysGainPct": 0.9065,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/330624647900.json",
        "marketValue": 2462.0747,
        "otherFees": 0,
        "pctOfPortfolio": 16.4178,
        "positionId": 330624647900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 159.3574,
        "quantity": 15.688,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/FXAIX.json",
        "symbolDescription": "FXAIX",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 2500.0,
        "totalGain": -37.9252,
        "totalGainPct": -1.517,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "JNJ", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "JNJ",
        },
        "Quick": {
            "change": 0.18,
            "changePct": 0.1039,
            "lastTrade": 173.28,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 16445469,
        },
        "adjPrevClose": 173.1,
        "commissions": 0,
        "costPerShare": 164.045,
        "dateAcquired": 1615525200000,
        "daysGain": 0.3599,
        "daysGainPct": 0.1039,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/155829489900.json",
        "marketValue": 346.56,
        "otherFees": 0,
        "pctOfPortfolio": 2.3109,
        "positionId": 155829489900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 164.0449,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/JNJ.json",
        "symbolDescription": "JNJ",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 328.0899,
        "totalGain": 18.4699,
        "totalGainPct": 5.6295,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "JPM", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "JPM",
        },
        "Quick": {
            "change": -1.26,
            "changePct": -0.8037,
            "lastTrade": 155.5,
            "lastTradeTime": 1691521655,
            "quoteStatus": "DELAYED",
            "volume": 5849290,
        },
        "adjPrevClose": 156.76,
        "commissions": 0,
        "costPerShare": 152.01,
        "dateAcquired": 1624334400000,
        "daysGain": -2.52,
        "daysGainPct": -0.8037,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/181276066900.json",
        "marketValue": 311,
        "otherFees": 0,
        "pctOfPortfolio": 2.0738,
        "positionId": 181276066900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 152.0099,
        "quantity": 2,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/JPM.json",
        "symbolDescription": "JPM",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 304.0199,
        "totalGain": 6.98,
        "totalGainPct": 2.2959,
    },
    {
        "Product": {
            "expiryDay": 0,
            "expiryMonth": 0,
            "expiryYear": 0,
            "productId": {"symbol": "WBD", "typeCode": "EQUITY"},
            "securityType": "EQ",
            "strikePrice": 0,
            "symbol": "WBD",
        },
        "Quick": {
            "change": -0.28,
            "changePct": -1.935,
            "lastTrade": 14.19,
            "lastTradeTime": 1691521658,
            "quoteStatus": "DELAYED",
            "volume": 13914827,
        },
        "adjPrevClose": 14.47,
        "commissions": 0,
        "costPerShare": 26.92,
        "dateAcquired": 1625112000000,
        "daysGain": -0.28,
        "daysGainPct": -1.935,
        "lotsDetails": "https://api.etrade.com/v1/accounts/TUAbfht8RVQigD2GIv4HAw/portfolio/246189189900.json",
        "marketValue": 14.1899,
        "otherFees": 0,
        "pctOfPortfolio": 0.0946,
        "positionId": 246189189900,
        "positionIndicator": "TYPE1",
        "positionType": "LONG",
        "pricePaid": 26.92,
        "quantity": 1,
        "quoteDetails": "https://api.etrade.com/v1/market/quote/WBD.json",
        "symbolDescription": "WBD",
        "todayCommissions": 0,
        "todayFees": 0,
        "todayPricePaid": 0,
        "todayQuantity": 0,
        "totalCost": 26.92,
        "totalGain": -12.73,
        "totalGainPct": -47.2882,
    },
]
